**Perform the following operations using Python data sets** 

**a. Create data subsets**

**b. Merge Data**

**c. Sort Data**

**d. Transposing Data**

**e. Shape and reshape Data**

In [1]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("temperatures.csv")

df

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN-FEB,MAR-MAY,JUN-SEP,OCT-DEC
0,1901,22.40,24.14,29.07,31.91,33.41,33.18,31.21,30.39,30.47,29.97,27.31,24.49,28.96,23.27,31.46,31.27,27.25
1,1902,24.93,26.58,29.77,31.78,33.73,32.91,30.92,30.73,29.80,29.12,26.31,24.04,29.22,25.75,31.76,31.09,26.49
2,1903,23.44,25.03,27.83,31.39,32.91,33.00,31.34,29.98,29.85,29.04,26.08,23.65,28.47,24.24,30.71,30.92,26.26
3,1904,22.50,24.73,28.21,32.02,32.64,32.07,30.36,30.09,30.04,29.20,26.36,23.63,28.49,23.62,30.95,30.66,26.40
4,1905,22.00,22.83,26.68,30.01,33.32,33.25,31.44,30.68,30.12,30.67,27.52,23.82,28.30,22.25,30.00,31.33,26.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,2013,24.56,26.59,30.62,32.66,34.46,32.44,31.07,30.76,31.04,30.27,27.83,25.37,29.81,25.58,32.58,31.33,27.83
113,2014,23.83,25.97,28.95,32.74,33.77,34.15,31.85,31.32,30.68,30.29,28.05,25.08,29.72,24.90,31.82,32.00,27.81
114,2015,24.58,26.89,29.07,31.87,34.09,32.48,31.88,31.52,31.55,31.04,28.10,25.67,29.90,25.74,31.68,31.87,28.27
115,2016,26.94,29.72,32.62,35.38,35.72,34.03,31.64,31.79,31.66,31.98,30.11,28.01,31.63,28.33,34.57,32.28,30.03
116,2017,26.45,29.46,31.60,34.95,35.84,33.82,31.88,31.72,32.22,32.29,29.60,27.18,31.42,27.95,34.13,32.41,29.69

In [6]:
# ----------------------------------------
# a. Create Data Subsets
# ----------------------------------------

# Select specific columns
subset_cols = df[['JAN', 'FEB']]

# Select rows using index
subset_rows = df.iloc[10:30]

# Conditional subset
subset_cond = df[df['MAR'] > 30]

subset_rows

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN-FEB,MAR-MAY,JUN-SEP,OCT-DEC
10,1911,23.22,24.58,27.04,31.27,33.78,32.23,31.44,30.80,30.10,29.43,25.70,23.71,28.62,23.90,30.70,31.14,26.31
11,1912,23.70,26.07,28.70,31.29,33.30,33.18,31.05,30.18,30.19,29.64,26.37,23.70,28.95,24.88,31.10,31.15,26.57
12,1913,23.71,24.79,27.62,32.02,33.07,32.23,30.65,30.48,30.33,29.42,26.28,23.56,28.67,24.25,30.89,30.92,26.42
13,1914,24.42,24.77,28.01,30.96,33.23,32.67,30.55,29.96,30.19,28.63,26.75,23.82,28.66,24.59,30.73,30.84,26.40
14,1915,22.60,23.84,27.62,31.36,34.20,33.10,31.52,30.79,30.79,30.08,27.62,23.78,28.94,23.22,31.06,31.51,27.19
15,1916,24.13,25.01,30.21,31.99,33.43,31.78,30.61,29.97,29.73,28.98,26.14,23.82,28.82,24.57,31.88,30.52,26.31
16,1917,23.68,25.35,27.86,30.61,31.93,31.44,30.56,29.86,29.07,27.90,25.94,23.43,28.11,24.52,30.06,30.24,25.74
17,1918,22.06,25.08,27.95,30.68,33.37,31.82,31.78,30.56,30.27,30.06,26.95,23.32,28.66,23.57,30.68,31.10,26.78
18,1919,23.32,24.10,28.58,31.55,33.38,32.48,30.79,30.10,29.81,29.44,26.85,23.50,28.66,23.71,31.17,30.80,26.60
19,1920,22.87,24.40,28.11,30.89,32.19,32.18,31.05,30.44,30.65,30.03,27.46,24.82,28.76,23.64,30.40,31.08,27.45
20,1921,23.57,24.24,30.04,32.47,35.84,32.40,31.21,29.83,29.79,28.51,26.61,24.17,28.86,23.91,32.05,30.81,26.43
21,1922,22.96,25.91,29.37,31.85,34.69,32.44,30.90,30.54,29.70,28.81,26.71,23.62,28.80,24.43,31.21,30.90,26.38
22,1923,23.25,24.20,28.61,32.37,33.23,33.56,30.41,29.96,30.01,28.57,26.68,24.05,28.74,23.73,31.40,30.98,26.43
23,1924,22.84,25.05,29.89,32.07,32.35,33.26,31.02,30.26,29.32,29.43,26.17,23.81,28.80,23.94,31.44,30.96,26.49
24,1925,22.56,24.58,29.32,32.53,32.56,31.88,30.31,30.08,30.41,29.43,26.20,24.15,28.67,23.57,31.47,30.67,26.59
25,1926,23.54,25.92,27.80,30.42,32.40,33.56,31.21,30.26,29.51,29.38,26.29,24.13,28.70,24.73,30.21,31.14,26.61
26,1927,23.23,24.28,28.09,31.50,32.58,32.33,30.66,29.92,30.27,29.55,26.30,24.33,28.59,23.76,30.72,30.80,26.73
27,1928,23.33,25.10,28.74,31.70,34.10,32.73,30.86,30.52,30.43,29.80,26.90,23.50,28.98,24.21,31.51,31.14,26.74
28,1929,23.05,24.01,29.88,31.59,33.68,32.54,30.81,30.05,30.73,28.61,27.19,23.02,28.76,23.53,31.72,31.03,26.28
29,1930,22.60,23.79,28.80,30.98,33.03,32.20,30.81,30.55,30.37,29.22,26.73,24.73,28.65,23.20,30.94,30.98,26.90

In [8]:
# ----------------------------------------
# b. Merge Data
# ----------------------------------------

# Create sample subsets
df1 = df.iloc[0:20]
df2 = df.iloc[20:40]

# Merge (concatenate)
merged_df = pd.concat([df1, df2])


merged_df

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN-FEB,MAR-MAY,JUN-SEP,OCT-DEC
0,1901,22.40,24.14,29.07,31.91,33.41,33.18,31.21,30.39,30.47,29.97,27.31,24.49,28.96,23.27,31.46,31.27,27.25
1,1902,24.93,26.58,29.77,31.78,33.73,32.91,30.92,30.73,29.80,29.12,26.31,24.04,29.22,25.75,31.76,31.09,26.49
2,1903,23.44,25.03,27.83,31.39,32.91,33.00,31.34,29.98,29.85,29.04,26.08,23.65,28.47,24.24,30.71,30.92,26.26
3,1904,22.50,24.73,28.21,32.02,32.64,32.07,30.36,30.09,30.04,29.20,26.36,23.63,28.49,23.62,30.95,30.66,26.40
4,1905,22.00,22.83,26.68,30.01,33.32,33.25,31.44,30.68,30.12,30.67,27.52,23.82,28.30,22.25,30.00,31.33,26.57
5,1906,22.28,23.69,27.31,31.93,34.11,32.19,31.01,30.30,29.92,29.55,27.60,24.72,28.73,23.03,31.11,30.86,27.29
6,1907,24.46,24.01,27.04,31.79,32.68,31.92,31.05,29.58,30.67,29.87,27.78,24.44,28.65,24.23,29.92,30.80,27.36
7,1908,23.57,25.26,28.86,32.42,33.02,33.12,30.61,29.55,29.59,29.35,26.88,23.73,28.83,24.42,31.43,30.72,26.64
8,1909,22.67,24.36,29.22,30.79,33.06,31.70,29.81,29.81,30.06,29.25,27.69,23.69,28.38,23.52,31.02,30.33,26.88
9,1910,23.24,25.16,28.48,31.42,33.51,31.84,30.42,29.86,29.82,28.91,26.32,23.37,28.53,24.20,31.14,30.48,26.20
10,1911,23.22,24.58,27.04,31.27,33.78,32.23,31.44,30.80,30.10,29.43,25.70,23.71,28.62,23.90,30.70,31.14,26.31
11,1912,23.70,26.07,28.70,31.29,33.30,33.18,31.05,30.18,30.19,29.64,26.37,23.70,28.95,24.88,31.10,31.15,26.57
12,1913,23.71,24.79,27.62,32.02,33.07,32.23,30.65,30.48,30.33,29.42,26.28,23.56,28.67,24.25,30.89,30.92,26.42
13,1914,24.42,24.77,28.01,30.96,33.23,32.67,30.55,29.96,30.19,28.63,26.75,23.82,28.66,24.59,30.73,30.84,26.40
14,1915,22.60,23.84,27.62,31.36,34.20,33.10,31.52,30.79,30.79,30.08,27.62,23.78,28.94,23.22,31.06,31.51,27.19
15,1916,24.13,25.01,30.21,31.99,33.43,31.78,30.61,29.97,29.73,28.98,26.14,23.82,28.82,24.57,31.88,30.52,26.31
16,1917,23.68,25.35,27.86,30.61,31.93,31.44,30.56,29.86,29.07,27.90,25.94,23.43,28.11,24.52,30.06,30.24,25.74
17,1918,22.06,25.08,27.95,30.68,33.37,31.82,31.78,30.56,30.27,30.06,26.95,23.32,28.66,23.57,30.68,31.10,26.78
18,1919,23.32,24.10,28.58,31.55,33.38,32.48,30.79,30.10,29.81,29.44,26.85,23.50,28.66,23.71,31.17,30.80,26.60
19,1920,22.87,24.40,28.11,30.89,32.19,32.18,31.05,30.44,30.65,30.03,27.46,24.82,28.76,23.64,30.40,31.08,27.45
20,1921,23.57,24.24,30.04,32.47,35.84,32.40,31.21,29.83,29.79,28.51,26.61,24.17,28.86,23.91,32.05,30.81,26.43
21,1922,22.96,25.91,29.37,31.85,34.69,32.44,30.90,30.54,29.70,28.81,26.71,23.62,28.80,24.43,31.21,30.90,26.38
22,1923,23.25,24.20,28.61,32.37,33.23,33.56,30.41,29.96,30.01,28.57,26.68,24.05,28.74,23.73,31.40,30.98,26.43
23,1924,22.84,25.05,29.89,32.07,32.35,33.26,31.02,30.26,29.32,29.43,26.17,23.81,28.80,23.94,31.44,30.96,26.49
24,1925,22.56,24.58,29.32,32.53,32.56,31.88,30.31,30.08,30.41,29.43,26.20,24.15,28.67,23.57,31.47,30.67,26.59
25,1926,23.54,25.92,27.80,30.42,32.40,33.56,31.21,30.26,29.51,29.38,26.29,24.13,28.70,24.73,30.21,31.14,26.61
26,1927,23.23,24.28,28.09,31.50,32.58,32.33,30.66,29.92,30.27,29.55,26.30,24.33,28.59,23.76,30.72,30.80,26.73
27,1928,23.33,25.10,28.74,31.70,34.10,32.73,30.86,30.52,30.43,29.80,26.90,23.50,28.98,24.21,31.51,31.14,26.74
28,1929,23.05,24.01,29.88,31.59,33.68,32.54,30.81,30.05,30.73,28.61,27.19,23.02,28.76,23.53,31.72,31.03,26.28
29,1930,22.60,23.79,28.80,30.98,33.03,32.20,30.81,30.55,30.37,29.22,26.73,24.73,28.65,23.20,30.94,30.98,26.90
30,1931,24.57,24.54,29.02,32.65,33.46,33.36,30.40,30.70,30.16,29.39,26.94,24.58,29.15,24.55,31.71,31.16,26.97
31,1932,24.13,24.89,28.82,32.08,32.61,32.91,30.99,30.34,30.83,29.68,27.35,24.52,29.09,24.51,31.17,31.25,27.18
32,1933,22.85,25.38,28.71,30.53,32.05,32.04,30.78,29.31,29.49,28.98,27.05,24.73,28.49,24.13,30.43,30.41,26.92
33,1934,22.76,26.29,28.61,31.95,33.29,32.67,31.04,30.10,30.77,29.75,26.77,24.31,29.03,24.53,31.28,31.22,26.94
34,1935,22.28,25.93,29.09,30.24,34.24,33.07,30.63,29.81,29.89,29.56,26.88,24.20,28.76,23.41,31.15,30.85,26.88
35,1936,23.10,25.11,28.07,31.52,33.93,31.46,30.55,30.32,30.40,29.86,26.47,23.72,28.71,24.11,31.17,30.68,26.69
36,1937,23.34,24.92,28.06,30.96,33.49,33.17,30.37,30.76,30.56,28.83,26.69,23.27,28.70,24.13,30.84,31.22,26.26
37,1938,22.95,23.68,28.90,32.33,33.99,31.10,30.69,30.24,30.33,29.35,26.45,24.34,28.70,23.31,31.74,30.59,26.71
38,1939,23.61,24.89,27.34,31.03,33.97,32.51,30.73,30.47,30.54,29.36,26.94,24.85,28.85,24.25,30.76,31.06,27.05
39,1940,23.79,25.12,27.31,31.38,33.29,32.48,30.92,29.96,30.51,29.97,27.47,24.40,28.88,24.46,30.66,30.93,27.24

In [9]:
# ----------------------------------------
# c. Sort Data
# ----------------------------------------

# Sort by a column (ascending/descending)
sorted_df = df.sort_values(by='ANNUAL', ascending=False)

sorted_df

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN-FEB,MAR-MAY,JUN-SEP,OCT-DEC
115,2016,26.94,29.72,32.62,35.38,35.72,34.03,31.64,31.79,31.66,31.98,30.11,28.01,31.63,28.33,34.57,32.28,30.03
116,2017,26.45,29.46,31.60,34.95,35.84,33.82,31.88,31.72,32.22,32.29,29.60,27.18,31.42,27.95,34.13,32.41,29.69
108,2009,25.27,27.75,30.57,33.09,34.09,33.73,31.77,31.84,31.60,30.75,27.59,25.53,30.30,26.51,32.57,32.24,27.96
101,2002,24.56,26.18,30.59,33.51,35.08,33.46,32.76,31.04,31.05,31.02,28.86,25.88,30.23,25.37,33.06,32.02,28.36
94,1995,24.44,26.93,29.92,32.83,34.45,34.48,31.39,30.91,31.24,30.93,28.51,26.21,30.18,25.68,32.40,32.01,28.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,1903,23.44,25.03,27.83,31.39,32.91,33.00,31.34,29.98,29.85,29.04,26.08,23.65,28.47,24.24,30.71,30.92,26.26
49,1950,23.56,24.48,27.78,31.16,33.22,32.35,30.35,30.01,29.22,28.96,26.79,24.00,28.47,24.02,30.72,30.48,26.58
8,1909,22.67,24.36,29.22,30.79,33.06,31.70,29.81,29.81,30.06,29.25,27.69,23.69,28.38,23.52,31.02,30.33,26.88
4,1905,22.00,22.83,26.68,30.01,33.32,33.25,31.44,30.68,30.12,30.67,27.52,23.82,28.30,22.25,30.00,31.33,26.57
16,1917,23.68,25.35,27.86,30.61,31.93,31.44,30.56,29.86,29.07,27.90,25.94,23.43,28.11,24.52,30.06,30.24,25.74

In [11]:
# ----------------------------------------
# d. Transposing Data
# ----------------------------------------

# Transpose dataframe (rows ↔ columns)
transposed_df = df.T

transposed_df

,0,1,2,3,4,5,6,7,8,9,...,107,108,109,110,111,112,113,114,115,116
YEAR,1901.00,1902.00,1903.00,1904.00,1905.00,1906.00,1907.00,1908.00,1909.00,1910.00,...,2008.00,2009.00,2010.00,2011.00,2012.00,2013.00,2014.00,2015.00,2016.00,2017.00
JAN,22.40,24.93,23.44,22.50,22.00,22.28,24.46,23.57,22.67,23.24,...,23.97,25.27,24.89,24.18,23.61,24.56,23.83,24.58,26.94,26.45
FEB,24.14,26.58,25.03,24.73,22.83,23.69,24.01,25.26,24.36,25.16,...,25.48,27.75,27.03,26.47,26.44,26.59,25.97,26.89,29.72,29.46
MAR,29.07,29.77,27.83,28.21,26.68,27.31,27.04,28.86,29.22,28.48,...,30.34,30.57,31.94,30.17,30.20,30.62,28.95,29.07,32.62,31.60
APR,31.91,31.78,31.39,32.02,30.01,31.93,31.79,32.42,30.79,31.42,...,32.13,33.09,34.07,31.70,32.46,32.66,32.74,31.87,35.38,34.95
MAY,33.41,33.73,32.91,32.64,33.32,34.11,32.68,33.02,33.06,33.51,...,33.86,34.09,34.43,34.33,34.30,34.46,33.77,34.09,35.72,35.84
JUN,33.18,32.91,33.00,32.07,33.25,32.19,31.92,33.12,31.70,31.84,...,32.15,33.73,33.22,33.02,33.60,32.44,34.15,32.48,34.03,33.82
JUL,31.21,30.92,31.34,30.36,31.44,31.01,31.05,30.61,29.81,30.42,...,31.24,31.77,31.24,31.41,31.88,31.07,31.85,31.88,31.64,31.88
AUG,30.39,30.73,29.98,30.09,30.68,30.30,29.58,29.55,29.81,29.86,...,30.69,31.84,30.77,30.92,30.96,30.76,31.32,31.52,31.79,31.72
SEP,30.47,29.80,29.85,30.04,30.12,29.92,30.67,29.59,30.06,29.82,...,30.92,31.60,30.65,30.81,30.65,31.04,30.68,31.55,31.66,32.22
OCT,29.97,29.12,29.04,29.20,30.67,29.55,29.87,29.35,29.25,28.91,...,30.81,30.75,30.47,30.85,30.20,30.27,30.29,31.04,31.98,32.29
NOV,27.31,26.31,26.08,26.36,27.52,27.60,27.78,26.88,27.69,26.32,...,28.15,27.59,28.01,28.31,28.11,27.83,28.05,28.10,30.11,29.60
DEC,24.49,24.04,23.65,23.63,23.82,24.72,24.44,23.73,23.69,23.37,...,25.91,25.53,24.88,25.60,25.34,25.37,25.08,25.67,28.01,27.18
ANNUAL,28.96,29.22,28.47,28.49,28.30,28.73,28.65,28.83,28.38,28.53,...,29.64,30.30,30.13,29.82,29.81,29.81,29.72,29.90,31.63,31.42
JAN-FEB,23.27,25.75,24.24,23.62,22.25,23.03,24.23,24.42,23.52,24.20,...,24.72,26.51,25.96,25.33,25.03,25.58,24.90,25.74,28.33,27.95
MAR-MAY,31.46,31.76,30.71,30.95,30.00,31.11,29.92,31.43,31.02,31.14,...,32.11,32.57,33.47,32.07,32.33,32.58,31.82,31.68,34.57,34.13
JUN-SEP,31.27,31.09,30.92,30.66,31.33,30.86,30.80,30.72,30.33,30.48,...,31.25,32.24,31.43,31.55,31.77,31.33,32.00,31.87,32.28,32.41
OCT-DEC,27.25,26.49,26.26,26.40,26.57,27.29,27.36,26.64,26.88,26.20,...,28.29,27.96,27.78,28.23,27.88,27.83,27.81,28.27,30.03,29.69

In [20]:
# ----------------------------------------
# e. Shape and Reshape Data
# ----------------------------------------

# Get shape (rows, columns)
print(df.shape)

# Convert DataFrame to NumPy array
arr = df.to_numpy()

# Reshape array (example)
reshaped_arr = arr.reshape(-1)
print(reshaped_arr)
# Example: reshape into 2 columns (only if size allows)
# reshaped_arr = arr.reshape(rows, cols)
# Replace 'col1', 'col2' with actual column names from your dataset.
# Reshaping only works if the total number of elements matches.

(117, 18)
[1901.     22.4    24.14 ...   34.13   32.41   29.69]